import Foundation

/// Traduce la demarcación fina que ya guarda FontApp a su división administrativa
/// superior. Las claves son exactamente los valores medidos en producción.
///
/// En Latinoamérica Natural Earth ya da la primera división (estados, provincias,
/// departamentos), así que cada demarcación es su propio admin1 y no agrupa nada: se
/// apunta igual para que `backfill-admin1` no se niegue y para que `/zones` no las
/// meta en «otras regiones». Puerto Rico va como `US-PR`, que es su código ISO 3166-2.
///
/// Noruega: Natural Earth trae los 19 fylker de antes de 2020 y aquí se agrupan en los
/// condados actuales (ISO 3166-2 de 2024): Hedmark + Oppland → Innlandet, las dos Agder
/// → Agder, Hordaland + Sogn og Fjordane → Vestland y las dos Trøndelag → Trøndelag.
///
/// Reino Unido: Natural Earth da condados y autoridades unitarias; se agrupan en las
/// cuatro naciones (GB-ENG, GB-SCT, GB-WLS, GB-NIR) según su propio campo `geonunit`.
///
/// Irlanda: Natural Earth da condados (y los tres de Dublín por separado); se agrupan
/// en las cuatro provincias (IE-C Connacht, IE-L Leinster, IE-M Munster, IE-U Ulster).
///
/// Bosnia: se agrupa por entidad con el campo `region` de Natural Earth, salvo dos
/// que el fichero etiqueta mal como República Srpska: el distrito de Brčko es BA-BRC y
/// el cantón de Posavina pertenece a la Federación (BA-BIH).
///
/// No se infiere por geometría: una provincia pertenece a una comunidad por definición.
/// Si entra un valor nuevo, queda sin clasificar hasta añadirlo explícitamente; inventar
/// aquí sería peor que devolver `nil`.
enum Admin1 {
    static func code(country: String?, region: String?) -> String? {
        guard let country, let region else { return nil }
        return byCountry[country]?[region]
    }

    static let byCountry: [String: [String: String]] = [
        "Albania": [
            "Berat": "AL-01", "Dibër": "AL-09", "Durrës": "AL-02", "Elbasan": "AL-03",
            "Fier": "AL-04", "Gjirokastër": "AL-05", "Korçë": "AL-06", "Kukës": "AL-07",
            "Lezhë": "AL-08", "Shkodër": "AL-10", "Tiranë": "AL-11", "Vlorë": "AL-12",
        ],
        "Andorra": [
            "Andorra la Vella": "AD-07", "Canillo": "AD-02", "Encamp": "AD-03",
            "Escaldes-Engordany": "AD-08", "La Massana": "AD-04", "Ordino": "AD-05",
            "Sant Julià de Lòria": "AD-06",
        ],
        "Argentina": [
            "Buenos Aires": "AR-B", "Catamarca": "AR-K", "Chaco": "AR-H", "Chubut": "AR-U",
            "Ciudad de Buenos Aires": "AR-C", "Corrientes": "AR-W", "Córdoba": "AR-X",
            "Entre Ríos": "AR-E", "Formosa": "AR-P", "Jujuy": "AR-Y", "La Pampa": "AR-L",
            "La Rioja": "AR-F", "Mendoza": "AR-M", "Misiones": "AR-N", "Neuquén": "AR-Q",
            "Río Negro": "AR-R", "Salta": "AR-A", "San Juan": "AR-J", "San Luis": "AR-D",
            "Santa Cruz": "AR-Z", "Santa Fe": "AR-S", "Santiago del Estero": "AR-G",
            "Tierra del Fuego": "AR-V", "Tucumán": "AR-T",
        ],
        "Austria": [
            "Burgenland": "AT-1", "Kärnten": "AT-2", "Niederösterreich": "AT-3",
            "Oberösterreich": "AT-4", "Salzburg": "AT-5", "Steiermark": "AT-6",
            "Tirol": "AT-7", "Vorarlberg": "AT-8", "Wien": "AT-9",
        ],
        "Belgium": [
            "Antwerp": "BE-VLG", "Brussels": "BE-BRU", "East Flanders": "BE-VLG",
            "Flemish Brabant": "BE-VLG", "Hainaut": "BE-WAL", "Liege": "BE-WAL",
            "Limburg": "BE-VLG", "Luxembourg": "BE-WAL", "Namur": "BE-WAL",
            "Walloon Brabant": "BE-WAL", "West Flanders": "BE-VLG",
        ],
        "Bolivia": [
            "Chuquisaca": "BO-H", "Cochabamba": "BO-C", "El Beni": "BO-B", "La Paz": "BO-L",
            "Oruro": "BO-O", "Potosí": "BO-P", "Santa Cruz": "BO-S",
        ],
        "Bosnia and Herzegovina": [
            "Banja Luka": "BA-SRP", "Bijeljina": "BA-SRP", "Bosnian Podrinje": "BA-BIH",
            "Brčko Distrikt": "BA-BRC", "Central Bosnia": "BA-BIH", "Doboj": "BA-SRP",
            "Foča": "BA-SRP", "Herzegovina-Neretva": "BA-BIH", "Posavina": "BA-BIH",
            "Sarajevo": "BA-BIH", "Sarajevo-romanija": "BA-SRP", "Trebinje": "BA-SRP",
            "Tuzla": "BA-BIH", "Una-Sana": "BA-BIH", "Vlasenica": "BA-SRP",
            "West Bosnia": "BA-BIH", "West Herzegovina": "BA-BIH", "Zenica-Doboj": "BA-BIH",
        ],
        "Brazil": [
            "Acre": "BR-AC", "Alagoas": "BR-AL", "Amazonas": "BR-AM", "Bahia": "BR-BA",
            "Ceará": "BR-CE", "Distrito Federal": "BR-DF", "Espírito Santo": "BR-ES",
            "Goiás": "BR-GO", "Maranhão": "BR-MA", "Mato Grosso": "BR-MT",
            "Mato Grosso do Sul": "BR-MS", "Minas Gerais": "BR-MG", "Paraná": "BR-PR",
            "Paraíba": "BR-PB", "Pará": "BR-PA", "Pernambuco": "BR-PE", "Piauí": "BR-PI",
            "Rio Grande do Norte": "BR-RN", "Rio Grande do Sul": "BR-RS",
            "Rio de Janeiro": "BR-RJ", "Rondônia": "BR-RO", "Roraima": "BR-RR",
            "Santa Catarina": "BR-SC", "Sergipe": "BR-SE", "São Paulo": "BR-SP",
            "Tocantins": "BR-TO",
        ],
        "Chile": [
            "Aisén del General Carlos Ibáñez del Campo": "CL-AI", "Antofagasta": "CL-AN",
            "Arica y Parinacota": "CL-AP", "Atacama": "CL-AT", "Bío-Bío": "CL-BI",
            "Coquimbo": "CL-CO", "La Araucanía": "CL-AR",
            "Libertador General Bernardo O'Higgins": "CL-LI", "Los Lagos": "CL-LL",
            "Los Ríos": "CL-LR", "Magallanes y Antártica Chilena": "CL-MA",
            "Maule": "CL-ML", "Región Metropolitana de Santiago": "CL-RM",
            "Valparaíso": "CL-VS", "Ñuble": "CL-NB",
        ],
        "Colombia": [
            "Amazonas": "CO-AMA", "Antioquia": "CO-ANT", "Arauca": "CO-ARA",
            "Atlántico": "CO-ATL", "Bogota": "CO-DC", "Bolívar": "CO-BOL",
            "Boyacá": "CO-BOY", "Caldas": "CO-CAL", "Caquetá": "CO-CAQ",
            "Casanare": "CO-CAS", "Cauca": "CO-CAU", "Cesar": "CO-CES", "Chocó": "CO-CHO",
            "Cundinamarca": "CO-CUN", "Córdoba": "CO-COR", "Huila": "CO-HUI",
            "La Guajira": "CO-LAG", "Magdalena": "CO-MAG", "Meta": "CO-MET",
            "Nariño": "CO-NAR", "Norte de Santander": "CO-NSA", "Putumayo": "CO-PUT",
            "Quindío": "CO-QUI", "Risaralda": "CO-RIS", "Santander": "CO-SAN",
            "Tolima": "CO-TOL", "Valle del Cauca": "CO-VAC", "Vichada": "CO-VID",
        ],
        "Costa Rica": [
            "Alajuela": "CR-A", "Cartago": "CR-C", "Guanacaste": "CR-G", "Heredia": "CR-H",
            "Limón": "CR-L", "Puntarenas": "CR-P", "San José": "CR-SJ",
        ],
        "Croatia": [
            "Bjelovarsko-bilogorska": "HR-07", "Brodsko-Posavska": "HR-12",
            "Dubrovacko-Neretvanska": "HR-19", "Grad Zagreb": "HR-21", "Istarska": "HR-18",
            "Karlovacka": "HR-04", "Koprivničko-Križevačka": "HR-06",
            "Krapinsko-Zagorska": "HR-02", "Licko-Senjska": "HR-09", "Medimurska": "HR-20",
            "Osjecko-Baranjska": "HR-14", "Primorsko-Goranska": "HR-08",
            "Sisacko-Moslavacka": "HR-03", "Splitsko-Dalmatinska": "HR-17",
            "Varaždinska": "HR-05", "Viroviticko-Podravska": "HR-10",
            "Vukovarsko-Srijemska": "HR-16", "Zadarska": "HR-13", "Zagrebacka": "HR-01",
            "Šibensko-Kninska": "HR-15",
        ],
        "Cuba": [
            "Artemisa": "CU-15", "Camagüey": "CU-09", "Ciego de Ávila": "CU-08",
            "Cienfuegos": "CU-06", "Ciudad de la Habana": "CU-03", "Granma": "CU-12",
            "Holguín": "CU-11", "Isla de la Juventud": "CU-99", "Las Tunas": "CU-10",
            "Matanzas": "CU-04", "Mayabeque": "CU-16", "Pinar del Río": "CU-01",
            "Sancti Spíritus": "CU-07", "Santiago de Cuba": "CU-13", "Villa Clara": "CU-05",
        ],
        "Czech Republic": [
            "Jihomoravský": "CZ-JM", "Jihočeský": "CZ-JC", "Karlovarský": "CZ-KA",
            "Královéhradecký": "CZ-KR", "Liberecký": "CZ-LI", "Moravskoslezský": "CZ-MO",
            "Olomoucký": "CZ-OL", "Pardubický": "CZ-PA", "Plzeňský": "CZ-PL",
            "Prague": "CZ-PR", "Středočeský": "CZ-ST", "Vysočina": "CZ-VY",
            "Zlínský": "CZ-ZL", "Ústecký": "CZ-US",
        ],
        "Dominican Republic": [
            "Azua": "DO-02", "Distrito Nacional": "DO-01", "Duarte": "DO-06",
            "Independencia": "DO-10", "La Altagracia": "DO-11", "La Vega": "DO-13",
            "María Trinidad Sánchez": "DO-14", "Monte Cristi": "DO-15",
            "Puerto Plata": "DO-18", "San Cristóbal": "DO-21", "San José de Ocoa": "DO-31",
            "San Juan": "DO-22", "Santiago": "DO-25", "Santo Domingo": "DO-32",
        ],
        "Ecuador": [
            "Azuay": "EC-A", "Bolivar": "EC-B", "Carchi": "EC-C", "Cañar": "EC-F",
            "Chimborazo": "EC-H", "Cotopaxi": "EC-X", "El Oro": "EC-O",
            "Esmeraldas": "EC-E", "Galápagos": "EC-W", "Guayas": "EC-G", "Imbabura": "EC-I",
            "Loja": "EC-L", "Los Rios": "EC-R", "Manabi": "EC-M", "Morona Santiago": "EC-S",
            "Napo": "EC-N", "Pastaza": "EC-Y", "Pichincha": "EC-P", "Santa Elena": "EC-SE",
            "Santo Domingo de los Tsáchilas": "EC-SD", "Sucumbios": "EC-U",
            "Tungurahua": "EC-T", "Zamora Chinchipe": "EC-Z",
        ],
        "El Salvador": [
            "La Unión": "SV-UN", "San Salvador": "SV-SS", "Santa Ana": "SV-SA",
            "Sonsonate": "SV-SO", "Usulután": "SV-US",
        ],
        "Finland": [
            "Central Finland": "FI-08", "Central Ostrobothnia": "FI-07",
            "Finland Proper": "FI-19", "Kainuu": "FI-05", "Kymenlaakso": "FI-09",
            "Lapland": "FI-10", "North Karelia": "FI-13", "Northern Ostrobothnia": "FI-14",
            "Northern Savonia": "FI-15", "Ostrobothnia": "FI-12", "Pirkanmaa": "FI-11",
            "Päijät-Häme": "FI-16", "Satakunta": "FI-17", "South Karelia": "FI-02",
            "Southern Ostrobothnia": "FI-03", "Southern Savonia": "FI-04",
            "Tavastia Proper": "FI-06", "Uusimaa": "FI-18", "Åland": "FI-01",
        ],
        "France": [
            "Ain": "FR-ARA", "Aisne": "FR-HDF", "Allier": "FR-ARA",
            "Alpes-Maritimes": "FR-PAC", "Alpes-de-Haute-Provence": "FR-PAC",
            "Ardennes": "FR-GES", "Ardèche": "FR-ARA", "Ariège": "FR-OCC", "Aube": "FR-GES",
            "Aude": "FR-OCC", "Aveyron": "FR-OCC", "Bas-Rhin": "FR-GES",
            "Bouches-du-Rhône": "FR-PAC", "Calvados": "FR-NOR", "Cantal": "FR-ARA",
            "Charente": "FR-NAQ", "Charente-Maritime": "FR-NAQ", "Cher": "FR-CVL",
            "Corrèze": "FR-NAQ", "Corse-du-Sud": "FR-20R", "Creuse": "FR-NAQ",
            "Côte-d'Or": "FR-BFC", "Côtes-d'Armor": "FR-BRE", "Deux-Sèvres": "FR-NAQ",
            "Dordogne": "FR-NAQ", "Doubs": "FR-BFC", "Drôme": "FR-ARA", "Essonne": "FR-IDF",
            "Eure": "FR-NOR", "Eure-et-Loir": "FR-CVL", "Finistère": "FR-BRE",
            "Gard": "FR-OCC", "Gers": "FR-OCC", "Gironde": "FR-NAQ",
            "Haute-Corse": "FR-20R", "Haute-Garonne": "FR-OCC", "Haute-Loire": "FR-ARA",
            "Haute-Marne": "FR-GES", "Haute-Rhin": "FR-GES", "Haute-Savoie": "FR-ARA",
            "Haute-Saône": "FR-BFC", "Haute-Vienne": "FR-NAQ", "Hautes-Alpes": "FR-PAC",
            "Hautes-Pyrénées": "FR-OCC", "Hauts-de-Seine": "FR-IDF", "Hérault": "FR-OCC",
            "Ille-et-Vilaine": "FR-BRE", "Indre": "FR-CVL", "Indre-et-Loire": "FR-CVL",
            "Isère": "FR-ARA", "Jura": "FR-BFC", "Landes": "FR-NAQ",
            "Loir-et-Cher": "FR-CVL", "Loire": "FR-ARA", "Loire-Atlantique": "FR-PDL",
            "Loiret": "FR-CVL", "Lot": "FR-OCC", "Lot-et-Garonne": "FR-NAQ",
            "Lozère": "FR-OCC", "Maine-et-Loire": "FR-PDL", "Manche": "FR-NOR",
            "Marne": "FR-GES", "Mayenne": "FR-PDL", "Meurthe-et-Moselle": "FR-GES",
            "Meuse": "FR-GES", "Morbihan": "FR-BRE", "Moselle": "FR-GES",
            "Nièvre": "FR-BFC", "Nord": "FR-HDF", "Oise": "FR-HDF", "Orne": "FR-NOR",
            "Paris": "FR-IDF", "Pas-de-Calais": "FR-HDF", "Puy-de-Dôme": "FR-ARA",
            "Pyrénées-Atlantiques": "FR-NAQ", "Pyrénées-Orientales": "FR-OCC",
            "Rhône": "FR-ARA", "Sarthe": "FR-PDL", "Savoie": "FR-ARA",
            "Saône-et-Loire": "FR-BFC", "Seien-et-Marne": "FR-IDF",
            "Seine-Maritime": "FR-NOR", "Seine-Saint-Denis": "FR-IDF", "Somme": "FR-HDF",
            "Tarn": "FR-OCC", "Tarn-et-Garonne": "FR-OCC",
            "Territoire de Belfort": "FR-BFC", "Val-d'Oise": "FR-IDF",
            "Val-de-Marne": "FR-IDF", "Var": "FR-PAC", "Vaucluse": "FR-PAC",
            "Vendée": "FR-PDL", "Vienne": "FR-NAQ", "Vosges": "FR-GES", "Yonne": "FR-BFC",
            "Yvelines": "FR-IDF",
        ],
        "Germany": [
            "Baden-Württemberg": "DE-BW", "Bayern": "DE-BY", "Berlin": "DE-BE",
            "Brandenburg": "DE-BB", "Bremen": "DE-HB", "Hamburg": "DE-HH",
            "Hessen": "DE-HE", "Mecklenburg-Vorpommern": "DE-MV", "Niedersachsen": "DE-NI",
            "Nordrhein-Westfalen": "DE-NW", "Rheinland-Pfalz": "DE-RP", "Saarland": "DE-SL",
            "Sachsen": "DE-SN", "Sachsen-Anhalt": "DE-ST", "Schleswig-Holstein": "DE-SH",
            "Thüringen": "DE-TH",
        ],
        "Greece": [
            "Anatoliki Makedonia kai Thraki": "GR-A", "Attiki": "GR-A1",
            "Ayion Oros": "GR-69", "Dytiki Ellada": "GR-G", "Dytiki Makedonia": "GR-C",
            "Ionioi Nisoi": "GR-F", "Ipeiros": "GR-D", "Kentriki Makedonia": "GR-B",
            "Kriti": "GR-M", "Notio Aigaio": "GR-L", "Peloponnisos": "GR-J",
            "Stereá Elláda": "GR-H", "Thessalia": "GR-E", "Voreio Aigaio": "GR-K",
        ],
        "Guatemala": [
            "Baja Verapaz": "GT-15", "Chimaltenango": "GT-04", "Guatemala": "GT-01",
            "Izabal": "GT-18", "Petén": "GT-17", "Sacatepéquez": "GT-03",
            "San Marcos": "GT-12", "Sololá": "GT-07", "Suchitepéquez": "GT-10",
            "Totonicapán": "GT-08",
        ],
        "Honduras": [
            "Atlántida": "HN-AT", "Cortés": "HN-CR", "Francisco Morazán": "HN-FM",
            "Gracias a Dios": "HN-GD", "Islas de la Bahía": "HN-IB", "La Paz": "HN-LP",
            "Lempira": "HN-LE", "Olancho": "HN-OL", "Yoro": "HN-YO",
        ],
        "Hungary": [
            "Baranya": "HU-BA", "Borsod-Abaúj-Zemplén": "HU-BZ", "Budapest": "HU-BU",
            "Bács-Kiskun": "HU-BK", "Békés": "HU-BE", "Békéscsaba": "HU-BC",
            "Csongrád": "HU-CS", "Debrecen": "HU-DE", "Dunaújváros": "HU-DU",
            "Eger": "HU-EG", "Fejér": "HU-FE", "Gyor-Moson-Sopron": "HU-GS",
            "Gyôr": "HU-GY", "Hajdú-Bihar": "HU-HB", "Heves": "HU-HE",
            "Hódmezôvásárhely": "HU-HV", "Jász-Nagykun-Szolnok": "HU-JN",
            "Kaposvár": "HU-KV", "Kecskemét": "HU-KM", "Komárom-Esztergom": "HU-KE",
            "Miskolc": "HU-MI", "Nagykanizsa": "HU-NK", "Nyíregyháza": "HU-NY",
            "Nógrád": "HU-NO", "Pest": "HU-PE", "Pécs": "HU-PS", "Salgótarján": "HU-ST",
            "Somogy": "HU-SO", "Sopron": "HU-SN", "Szabolcs-Szatmár-Bereg": "HU-SZ",
            "Szeged": "HU-SD", "Szekszárd": "HU-SS", "Szolnok": "HU-SK",
            "Szombathely": "HU-SH", "Székesfehérvár": "HU-SF", "Tatabánya": "HU-TB",
            "Tolna": "HU-TO", "Vas": "HU-VA", "Veszprém": "HU-VE", "Zala": "HU-ZA",
            "Zalaegerszeg": "HU-ZE", "Érd": "HU-ED",
        ],
        "Ireland": [
            "Carlow": "IE-L", "Cavan": "IE-U", "Clare": "IE-M", "Cork": "IE-M",
            "Donegal": "IE-U", "Dublin": "IE-L", "Dún Laoghaire–Rathdown": "IE-L",
            "Fingal": "IE-L", "Galway": "IE-C", "Kerry": "IE-M", "Kildare": "IE-L",
            "Kilkenny": "IE-L", "Laoighis": "IE-L", "Leitrim": "IE-C", "Limerick": "IE-M",
            "Longford": "IE-L", "Louth": "IE-L", "Mayo": "IE-C", "Meath": "IE-L",
            "Monaghan": "IE-U", "North Tipperary": "IE-M", "Offaly": "IE-L",
            "Roscommon": "IE-C", "Sligo": "IE-C", "South Dublin": "IE-L",
            "South Tipperary": "IE-M", "Waterford": "IE-M", "Westmeath": "IE-L",
            "Wexford": "IE-L", "Wicklow": "IE-L",
        ],
        "Italy": [
            "Agrigento": "IT-82", "Alessandria": "IT-21", "Ancona": "IT-57",
            "Aoste": "IT-23", "Arezzo": "IT-52", "Ascoli Piceno": "IT-57", "Asti": "IT-21",
            "Avellino": "IT-72", "Bari": "IT-75", "Barletta-Andria Trani": "IT-75",
            "Belluno": "IT-34", "Benevento": "IT-72", "Bergamo": "IT-25", "Biella": "IT-21",
            "Bologna": "IT-45", "Bozen": "IT-32", "Brescia": "IT-25", "Brindisi": "IT-75",
            "Cagliari": "IT-88", "Caltanissetta": "IT-82", "Campobasso": "IT-67",
            "Carbonia-Iglesias": "IT-88", "Caserta": "IT-72", "Catania": "IT-82",
            "Catanzaro": "IT-78", "Chieti": "IT-65", "Como": "IT-25", "Cosenza": "IT-78",
            "Cremona": "IT-25", "Crotene": "IT-78", "Cuneo": "IT-21", "Enna": "IT-82",
            "Fermo": "IT-57", "Ferrara": "IT-45", "Firenze": "IT-52", "Foggia": "IT-75",
            "Forlì-Cesena": "IT-45", "Frosinone": "IT-62", "Genova": "IT-42",
            "Gorizia": "IT-36", "Grosseto": "IT-52", "Imperia": "IT-42", "Isernia": "IT-67",
            "L'Aquila": "IT-65", "La Spezia": "IT-42", "Latina": "IT-62", "Lecce": "IT-75",
            "Lecco": "IT-25", "Livorno": "IT-52", "Lodi": "IT-25", "Lucca": "IT-52",
            "Macerata": "IT-57", "Mantova": "IT-25", "Massa-Carrara": "IT-52",
            "Matera": "IT-77", "Medio Campidano": "IT-88", "Messina": "IT-82",
            "Milano": "IT-25", "Modena": "IT-45", "Monza e Brianza": "IT-25",
            "Napoli": "IT-72", "Novara": "IT-21", "Nuoro": "IT-88", "Ogliastra": "IT-88",
            "Olbia-Tempio": "IT-88", "Oristrano": "IT-88", "Padova": "IT-34",
            "Palermo": "IT-82", "Parma": "IT-45", "Pavia": "IT-25", "Perugia": "IT-55",
            "Pesaro e Urbino": "IT-57", "Pescara": "IT-65", "Piacenza": "IT-45",
            "Pisa": "IT-52", "Pistoia": "IT-52", "Pordenone": "IT-36", "Potenza": "IT-77",
            "Prato": "IT-52", "Ragusa": "IT-82", "Ravenna": "IT-45",
            "Reggio Calabria": "IT-78", "Reggio Emilia": "IT-45", "Rieti": "IT-62",
            "Rimini": "IT-45", "Roma": "IT-62", "Rovigo": "IT-34", "Salerno": "IT-72",
            "Sassari": "IT-88", "Savona": "IT-42", "Siena": "IT-52", "Siracusa": "IT-82",
            "Sondrio": "IT-25", "Taranto": "IT-75", "Teramo": "IT-65", "Terni": "IT-55",
            "Trapani": "IT-82", "Trento": "IT-32", "Treviso": "IT-34", "Trieste": "IT-36",
            "Turin": "IT-21", "Udine": "IT-36", "Varese": "IT-25", "Venezia": "IT-34",
            "Verbano-Cusio-Ossola": "IT-21", "Vercelli": "IT-21", "Verona": "IT-34",
            "Vibo Valentia": "IT-78", "Vicenza": "IT-34", "Viterbo": "IT-62",
        ],
        "Mexico": [
            "Aguascalientes": "MX-AGU", "Baja California": "MX-BCN",
            "Baja California Sur": "MX-BCS", "Campeche": "MX-CAM", "Chiapas": "MX-CHP",
            "Chihuahua": "MX-CHH", "Coahuila": "MX-COA", "Colima": "MX-COL",
            "Distrito Federal": "MX-CMX", "Durango": "MX-DUR", "Guanajuato": "MX-GUA",
            "Guerrero": "MX-GRO", "Hidalgo": "MX-HID", "Jalisco": "MX-JAL",
            "Michoacán": "MX-MIC", "Morelos": "MX-MOR", "México": "MX-MEX",
            "Nayarit": "MX-NAY", "Nuevo León": "MX-NLE", "Oaxaca": "MX-OAX",
            "Puebla": "MX-PUE", "Querétaro": "MX-QUE", "Quintana Roo": "MX-ROO",
            "San Luis Potosí": "MX-SLP", "Sinaloa": "MX-SIN", "Sonora": "MX-SON",
            "Tabasco": "MX-TAB", "Tamaulipas": "MX-TAM", "Tlaxcala": "MX-TLA",
            "Veracruz": "MX-VER", "Yucatán": "MX-YUC", "Zacatecas": "MX-ZAC",
        ],
        "Montenegro": [
            "Andrijevica": "ME-01", "Bar": "ME-02", "Berane": "ME-03",
            "Bijelo Polje": "ME-04", "Budva": "ME-05", "Cetinje": "ME-06",
            "Danilovgrad": "ME-07", "Herceg Novi": "ME-08", "Kolašin": "ME-09",
            "Kotor": "ME-10", "Mojkovac": "ME-11", "Nikšic": "ME-12", "Plav": "ME-13",
            "Pljevlja": "ME-14", "Plužine": "ME-15", "Podgorica": "ME-16",
            "Rožaje": "ME-17", "Tivat": "ME-19", "Ulcinj": "ME-20", "Šavnik": "ME-18",
            "Žabljak": "ME-21",
        ],
        "Netherlands": [
            "Drenthe": "NL-DR", "Flevoland": "NL-FL", "Friesland": "NL-FR",
            "Gelderland": "NL-GE", "Groningen": "NL-GR", "Limburg": "NL-LI",
            "Noord-Brabant": "NL-NB", "Noord-Holland": "NL-NH", "Overijssel": "NL-OV",
            "Utrecht": "NL-UT", "Zeeland": "NL-ZE", "Zuid-Holland": "NL-ZH",
        ],
        "Nicaragua": [
            "Atlántico Norte": "NI-AN", "Atlántico Sur": "NI-AS", "Boaco": "NI-BO",
            "Carazo": "NI-CA", "Chinandega": "NI-CI", "León": "NI-LE", "Madriz": "NI-MD",
            "Managua": "NI-MN", "Rivas": "NI-RI",
        ],
        "Norway": [
            "Akershus": "NO-32", "Aust-Agder": "NO-42", "Buskerud": "NO-33",
            "Finnmark": "NO-56", "Hedmark": "NO-34", "Hordaland": "NO-46",
            "Møre og Romsdal": "NO-15", "Nord-Trøndelag": "NO-50", "Nordland": "NO-18",
            "Oppland": "NO-34", "Oslo": "NO-03", "Rogaland": "NO-11",
            "Sogn og Fjordane": "NO-46", "Svalbard": "NO-21", "Sør-Trøndelag": "NO-50",
            "Telemark": "NO-40", "Troms": "NO-55", "Vest-Agder": "NO-42",
            "Vestfold": "NO-39", "Østfold": "NO-31",
        ],
        "Panama": [
            "Bocas del Toro": "PA-1", "Chiriquí": "PA-4", "Coclé": "PA-2", "Colón": "PA-3",
            "Panama": "PA-8", "Veraguas": "PA-9",
        ],
        "Paraguay": [
            "Alto Paraná": "PY-10", "Amambay": "PY-13", "Asunción": "PY-ASU",
            "Boquerón": "PY-19", "Canindeyú": "PY-14", "Central": "PY-11",
            "Cordillera": "PY-3", "Guairá": "PY-4", "Itapúa": "PY-7", "Misiones": "PY-8",
            "Paraguarí": "PY-9",
        ],
        "Peru": [
            "Amazonas": "PE-AMA", "Ancash": "PE-ANC", "Apurímac": "PE-APU",
            "Arequipa": "PE-ARE", "Ayacucho": "PE-AYA", "Cajamarca": "PE-CAJ",
            "Callao": "PE-CAL", "Cusco": "PE-CUS", "Huancavelica": "PE-HUV",
            "Huánuco": "PE-HUC", "Ica": "PE-ICA", "Junín": "PE-JUN",
            "La Libertad": "PE-LAL", "Lambayeque": "PE-LAM", "Lima": "PE-LIM",
            "Lima Province": "PE-LMA", "Loreto": "PE-LOR", "Madre de Dios": "PE-MDD",
            "Puno": "PE-PUN", "San Martín": "PE-SAM", "Tacna": "PE-TAC",
        ],
        "Poland": [
            "Greater Poland": "PL-WP", "Kuyavian-Pomeranian": "PL-KP",
            "Lesser Poland": "PL-MA", "Lower Silesian": "PL-DS", "Lublin": "PL-LU",
            "Lubusz": "PL-LB", "Masovian": "PL-MZ", "Opole": "PL-OP", "Podlachian": "PL-PD",
            "Pomeranian": "PL-PM", "Silesian": "PL-SL", "Subcarpathian": "PL-PK",
            "Warmian-Masurian": "PL-WN", "West Pomeranian": "PL-ZP", "Łódź": "PL-LD",
            "Świętokrzyskie": "PL-SK",
        ],
        "Portugal": [
            "Aveiro": "PT-01", "Azores": "PT-20", "Beja": "PT-02", "Braga": "PT-03",
            "Bragança": "PT-04", "Castelo Branco": "PT-05", "Coimbra": "PT-06",
            "Faro": "PT-08", "Guarda": "PT-09", "Leiria": "PT-10", "Lisboa": "PT-11",
            "Madeira": "PT-30", "Portalegre": "PT-12", "Porto": "PT-13",
            "Santarém": "PT-14", "Setúbal": "PT-15", "Viana do Castelo": "PT-16",
            "Vila Real": "PT-17", "Viseu": "PT-18", "Évora": "PT-07",
        ],
        "Puerto Rico": [
            "Puerto Rico": "US-PR",
        ],
        "Slovenia": [
            "Ajdovščina": "SI-001", "Bistrica ob Sotli": "SI-149", "Bled": "SI-003",
            "Bloke": "SI-150", "Bohinj": "SI-004", "Borovnica": "SI-005", "Bovec": "SI-006",
            "Braslovce": "SI-151", "Brda": "SI-007", "Brezovica": "SI-008",
            "Brežice": "SI-009", "Cankova": "SI-152", "Celje": "SI-011",
            "Cerklje na Gorenjskem": "SI-012", "Cerknica": "SI-013", "Cerkno": "SI-014",
            "Crnomelj": "SI-017", "Divaca": "SI-019", "Dobrepolje": "SI-020",
            "Dobrna": "SI-155", "Dobrova-Polhov Gradec": "SI-021", "Dobrovnik": "SI-156",
            "Dol pri Ljubljani": "SI-022", "Dolenjske Toplice": "SI-157",
            "Domžale": "SI-023", "Dravograd": "SI-025", "Duplek": "SI-026",
            "Gorenja vas-Poljane": "SI-027", "Gorišnica": "SI-028",
            "Gornja Radgona": "SI-029", "Gornji Grad": "SI-030",
            "Gornji Petrovci": "SI-031", "Grosuplje": "SI-032", "Hajdina": "SI-159",
            "Hoce-Slivnica": "SI-160", "Hodoš": "SI-161", "Horjul": "SI-162",
            "Hrastnik": "SI-034", "Hrpelje-Kozina": "SI-035", "Idrija": "SI-036",
            "Ig": "SI-037", "Ilirska Bistrica": "SI-038", "Ivancna Gorica": "SI-039",
            "Izola": "SI-040", "Jesenice": "SI-041", "Jezersko": "SI-163",
            "Kamnik": "SI-043", "Kanal": "SI-044", "Kidricevo": "SI-045",
            "Kobarid": "SI-046", "Kocevje": "SI-048", "Komen": "SI-049",
            "Komenda": "SI-164", "Koper": "SI-050", "Kostel": "SI-165", "Kozje": "SI-051",
            "Kranj": "SI-052", "Kranjska Gora": "SI-053", "Krško": "SI-054",
            "Laško": "SI-057", "Lenart": "SI-058", "Lendava": "SI-059", "Litija": "SI-060",
            "Ljubljana": "SI-061", "Ljubno": "SI-062", "Ljutomer": "SI-063",
            "Logatec": "SI-064", "Lovrenc na Pohorju": "SI-167", "Loška dolina": "SI-065",
            "Loški Potok": "SI-066", "Luce": "SI-067", "Lukovica": "SI-068",
            "Majšperk": "SI-069", "Maribor": "SI-070", "Markovci": "SI-168",
            "Medvode": "SI-071", "Mengeš": "SI-072", "Metlika": "SI-073",
            "Miren-Kostanjevica": "SI-075", "Mirna Pec": "SI-170", "Mislinja": "SI-076",
            "Moravce": "SI-077", "Moravske Toplice": "SI-078", "Mozirje": "SI-079",
            "Murska Sobota": "SI-080", "Muta": "SI-081", "Naklo": "SI-082",
            "Nazarje": "SI-083", "Nova Goriška": "SI-084", "Novo Mesto": "SI-085",
            "Ormož": "SI-087", "Pesnica": "SI-089", "Piran": "SI-090", "Pivka": "SI-091",
            "Podcetrtek": "SI-092", "Podlehnik": "SI-172", "Podvelka": "SI-093",
            "Postojna": "SI-094", "Preddvor": "SI-095", "Ptuj": "SI-096",
            "Puconci": "SI-097", "Race-Fram": "SI-098", "Radece": "SI-099",
            "Radenci": "SI-100", "Radlje ob Dravi": "SI-101", "Radovljica": "SI-102",
            "Ravne na Koroškem": "SI-103", "Razkrižje": "SI-176", "Ribnica": "SI-104",
            "Ribnica na Pohorju": "SI-177", "Rogatec": "SI-107",
            "Rogaška Slatina": "SI-106", "Rogašovci": "SI-105", "Ruše": "SI-108",
            "Selnica ob Dravi": "SI-178", "Semic": "SI-109", "Sevnica": "SI-110",
            "Sežana": "SI-111", "Slovenj Gradec": "SI-112", "Slovenska Bistrica": "SI-113",
            "Slovenske Konjice": "SI-114", "Sodražica": "SI-179", "Solcava": "SI-180",
            "Sveta Ana": "SI-181", "Tabor": "SI-184", "Tolmin": "SI-128",
            "Trbovlje": "SI-129", "Trebnje": "SI-130", "Trzin": "SI-186", "Tržič": "SI-131",
            "Velenje": "SI-133", "Velika Polana": "SI-187", "Velike Lašče": "SI-134",
            "Vipava": "SI-136", "Vitanje": "SI-137", "Vodice": "SI-138", "Vojnik": "SI-139",
            "Vransko": "SI-189", "Vrhnika": "SI-140", "Vuzenica": "SI-141",
            "Zasavska": "SI-05", "Zrece": "SI-144", "Črna na Koroškem": "SI-016",
            "Šempeter-Vrtojba": "SI-183", "Šentilj": "SI-118", "Šentjernej": "SI-119",
            "Šentjur pri Celju": "SI-120", "Šenčur": "SI-117", "Škocjan": "SI-121",
            "Škofja Loka": "SI-122", "Škofljica": "SI-123", "Šmarje pri Jelšah": "SI-124",
            "Šmartno in Litiji": "SI-194", "Šmartno ob Paki": "SI-125", "Šoštanj": "SI-126",
            "Žalec": "SI-190", "Železniki": "SI-146", "Žetale": "SI-191", "Žiri": "SI-147",
            "Žirovnica": "SI-192", "Žužemberk": "SI-193",
        ],
        "Spain": [
            "Albacete": "ES-CM", "Alicante": "ES-VC", "Almería": "ES-AN",
            "Asturias": "ES-AS", "Badajoz": "ES-EX", "Baleares": "ES-IB",
            "Barcelona": "ES-CT", "Bizkaia": "ES-PV", "Burgos": "ES-CL",
            "Cantabria": "ES-CB", "Castellón": "ES-VC", "Ceuta": "ES-CE",
            "Ciudad Real": "ES-CM", "Cuenca": "ES-CM", "Cáceres": "ES-EX",
            "Cádiz": "ES-AN", "Córdoba": "ES-AN", "Gipuzkoa": "ES-PV",
            "Gerona": "ES-CT", "Girona": "ES-CT", "Granada": "ES-AN", "Guadalajara": "ES-CM",
            "Huelva": "ES-AN", "Huesca": "ES-AR", "Jaén": "ES-AN",
            "La Coruña": "ES-GA", "La Rioja": "ES-RI", "Las Palmas": "ES-CN",
            "León": "ES-CL", "Lérida": "ES-CT", "Lleida": "ES-CT", "Lugo": "ES-GA",
            "Madrid": "ES-MD",
            "Melilla": "ES-ML", "Murcia": "ES-MC", "Málaga": "ES-AN",
            "Navarra": "ES-NC", "Orense": "ES-GA", "Palencia": "ES-CL",
            "Pontevedra": "ES-GA", "Salamanca": "ES-CL", "Santa Cruz de Tenerife": "ES-CN",
            "Segovia": "ES-CL", "Sevilla": "ES-AN", "Soria": "ES-CL",
            "Tarragona": "ES-CT", "Teruel": "ES-AR", "Toledo": "ES-CM",
            "Valencia": "ES-VC", "Valladolid": "ES-CL", "Zamora": "ES-CL",
            "Zaragoza": "ES-AR", "Álava": "ES-PV", "Ávila": "ES-CL",
        ],
        "Sweden": [
            "Blekinge": "SE-K", "Dalarna": "SE-W", "Gotland": "SE-I",
            "Gävleborg": "SE-X", "Halland": "SE-N", "Jämtland": "SE-Z",
            "Jönköping": "SE-F", "Kalmar": "SE-H", "Kronoberg": "SE-G",
            "Norrbotten": "SE-BD", "Orebro": "SE-T", "Skåne": "SE-M",
            "Stockholm": "SE-AB", "Södermanland": "SE-D", "Uppsala": "SE-C",
            "Värmland": "SE-S", "Västerbotten": "SE-AC", "Västernorrland": "SE-Y",
            "Västmanland": "SE-U", "Västra Götaland": "SE-O", "Östergötland": "SE-E",
        ],
        "Switzerland": [
            "Aargau": "CH-AG", "Appenzell Ausserrhoden": "CH-AR",
            "Appenzell Innerrhoden": "CH-AI", "Basel-Landschaft": "CH-BL",
            "Basel-Stadt": "CH-BS", "Bern": "CH-BE", "Fribourg": "CH-FR",
            "Genève": "CH-GE", "Glarus": "CH-GL", "Graubünden": "CH-GR",
            "Jura": "CH-JU", "Lucerne": "CH-LU", "Neuchâtel": "CH-NE",
            "Nidwalden": "CH-NW", "Obwalden": "CH-OW", "Sankt Gallen": "CH-SG",
            "Schaffhausen": "CH-SH", "Schwyz": "CH-SZ", "Solothurn": "CH-SO",
            "Thurgau": "CH-TG", "Ticino": "CH-TI", "Uri": "CH-UR",
            "Valais": "CH-VS", "Vaud": "CH-VD", "Zug": "CH-ZG", "Zürich": "CH-ZH",
        ],
        "United Kingdom": [
            "Aberdeen": "GB-SCT", "Aberdeenshire": "GB-SCT", "Anglesey": "GB-WLS",
            "Angus": "GB-SCT", "Antrim": "GB-NIR", "Ards": "GB-NIR",
            "Argyll and Bute": "GB-SCT", "Armagh": "GB-NIR", "Ballymena": "GB-NIR",
            "Ballymoney": "GB-NIR", "Banbridge": "GB-NIR", "Barnet": "GB-ENG",
            "Barnsley": "GB-ENG", "Bath and North East Somerset": "GB-ENG",
            "Bedford": "GB-ENG", "Belfast": "GB-NIR", "Bexley": "GB-ENG",
            "Birmingham": "GB-ENG", "Blackpool": "GB-ENG", "Bournemouth": "GB-ENG",
            "Bracknell Forest": "GB-ENG", "Bradford": "GB-ENG", "Brent": "GB-ENG",
            "Bridgend": "GB-WLS", "Brighton and Hove": "GB-ENG", "Bristol": "GB-ENG",
            "Bromley": "GB-ENG", "Buckinghamshire": "GB-ENG", "Caerphilly": "GB-WLS",
            "Calderdale": "GB-ENG", "Cambridgeshire": "GB-ENG", "Camden": "GB-ENG",
            "Cardiff": "GB-WLS", "Carmarthenshire": "GB-WLS", "Castlereagh": "GB-NIR",
            "Central Bedfordshire": "GB-ENG", "Ceredigion": "GB-WLS",
            "Cheshire East": "GB-ENG", "Cheshire West and Chester": "GB-ENG",
            "City": "GB-ENG", "Clackmannanshire": "GB-SCT", "Conwy": "GB-WLS",
            "Cornwall": "GB-ENG", "Coventry": "GB-ENG", "Croydon": "GB-ENG",
            "Cumbria": "GB-ENG", "Denbighshire": "GB-WLS", "Derbyshire": "GB-ENG",
            "Devon": "GB-ENG", "Doncaster": "GB-ENG", "Dorset": "GB-ENG", "Down": "GB-NIR",
            "Dudley": "GB-ENG", "Dumfries and Galloway": "GB-SCT", "Dundee": "GB-SCT",
            "Dungannon": "GB-NIR", "Durham": "GB-ENG", "Ealing": "GB-ENG",
            "East Ayrshire": "GB-SCT", "East Dunbartonshire": "GB-SCT",
            "East Lothian": "GB-SCT", "East Renfrewshire": "GB-SCT",
            "East Riding of Yorkshire": "GB-ENG", "East Sussex": "GB-ENG",
            "Edinburgh": "GB-SCT", "Eilean Siar": "GB-SCT", "Enfield": "GB-ENG",
            "Essex": "GB-ENG", "Falkirk": "GB-SCT", "Fermanagh": "GB-NIR", "Fife": "GB-SCT",
            "Flintshire": "GB-WLS", "Gateshead": "GB-ENG", "Glasgow": "GB-SCT",
            "Gloucestershire": "GB-ENG", "Greenwich": "GB-ENG", "Gwynedd": "GB-WLS",
            "Hackney": "GB-ENG", "Halton": "GB-ENG", "Hammersmith and Fulham": "GB-ENG",
            "Hampshire": "GB-ENG", "Haringey": "GB-ENG", "Hartlepool": "GB-ENG",
            "Herefordshire": "GB-ENG", "Hertfordshire": "GB-ENG", "Highland": "GB-SCT",
            "Hillingdon": "GB-ENG", "Hounslow": "GB-ENG", "Inverclyde": "GB-SCT",
            "Isle of Wight": "GB-ENG", "Isles of Scilly": "GB-ENG", "Islington": "GB-ENG",
            "Kensington and Chelsea": "GB-ENG", "Kent": "GB-ENG",
            "Kingston upon Thames": "GB-ENG", "Kirklees": "GB-ENG", "Lambeth": "GB-ENG",
            "Lancashire": "GB-ENG", "Larne": "GB-NIR", "Leeds": "GB-ENG",
            "Leicester": "GB-ENG", "Leicestershire": "GB-ENG", "Lewisham": "GB-ENG",
            "Limavady": "GB-NIR", "Lincolnshire": "GB-ENG", "Liverpool": "GB-ENG",
            "Luton": "GB-ENG", "Magherafelt": "GB-NIR", "Manchester": "GB-ENG",
            "Medway": "GB-ENG", "Merton": "GB-ENG", "Mid Ulster": "GB-NIR",
            "Midlothian": "GB-SCT", "Milton Keynes": "GB-ENG", "Monmouthshire": "GB-WLS",
            "Moray": "GB-SCT", "Moyle": "GB-NIR", "Neath Port Talbot": "GB-WLS",
            "Newham": "GB-ENG", "Newport": "GB-WLS", "Newry and Mourne": "GB-NIR",
            "Newtownabbey": "GB-NIR", "Norfolk": "GB-ENG", "North Ayshire": "GB-SCT",
            "North Down": "GB-NIR", "North East Lincolnshire": "GB-ENG",
            "North Lanarkshire": "GB-SCT", "North Lincolnshire": "GB-ENG",
            "North Somerset": "GB-ENG", "North Tyneside": "GB-ENG",
            "North Yorkshire": "GB-ENG", "Northamptonshire": "GB-ENG",
            "Northumberland": "GB-ENG", "Nottingham": "GB-ENG", "Nottinghamshire": "GB-ENG",
            "Oldham": "GB-ENG", "Omagh": "GB-NIR", "Orkney": "GB-SCT",
            "Oxfordshire": "GB-ENG", "Pembrokeshire": "GB-WLS",
            "Perthshire and Kinross": "GB-SCT", "Peterborough": "GB-ENG",
            "Plymouth": "GB-ENG", "Poole": "GB-ENG", "Portsmouth": "GB-ENG",
            "Powys": "GB-WLS", "Redbridge": "GB-ENG", "Redcar and Cleveland": "GB-ENG",
            "Renfrewshire": "GB-SCT", "Rhondda, Cynon, Taff": "GB-WLS",
            "Richmond upon Thames": "GB-ENG", "Rotherham": "GB-ENG",
            "Royal Borough of Windsor and Maidenhead": "GB-ENG", "Rutland": "GB-ENG",
            "Salford": "GB-ENG", "Sandwell": "GB-ENG", "Scottish Borders": "GB-SCT",
            "Sefton": "GB-ENG", "Sheffield": "GB-ENG", "Shetland Islands": "GB-SCT",
            "Shropshire": "GB-ENG", "Slough": "GB-ENG", "Solihull": "GB-ENG",
            "Somerset": "GB-ENG", "South Ayrshire": "GB-SCT",
            "South Gloucestershire": "GB-ENG", "South Lanarkshire": "GB-SCT",
            "South Tyneside": "GB-ENG", "Southampton": "GB-ENG",
            "Southend-on-Sea": "GB-ENG", "Southwark": "GB-ENG", "Staffordshire": "GB-ENG",
            "Stirling": "GB-SCT", "Stockport": "GB-ENG", "Stoke-on-Trent": "GB-ENG",
            "Strabane": "GB-NIR", "Suffolk": "GB-ENG", "Surrey": "GB-ENG",
            "Swansea": "GB-WLS", "Swindon": "GB-ENG", "Tameside": "GB-ENG",
            "Torbay": "GB-ENG", "Torfaen": "GB-WLS", "Tower Hamlets": "GB-ENG",
            "Vale of Glamorgan": "GB-WLS", "Wakefield": "GB-ENG",
            "Waltham Forest": "GB-ENG", "Wandsworth": "GB-ENG", "Warrington": "GB-ENG",
            "Warwickshire": "GB-ENG", "West Berkshire": "GB-ENG",
            "West Dunbartonshire": "GB-SCT", "West Lothian": "GB-SCT",
            "West Sussex": "GB-ENG", "Westminster": "GB-ENG", "Wigan": "GB-ENG",
            "Wiltshire": "GB-ENG", "Wokingham": "GB-ENG", "Worcestershire": "GB-ENG",
            "Wrexham": "GB-WLS", "York": "GB-ENG",
        ],
        "Uruguay": [
            "Canelones": "UY-CA", "Colonia": "UY-CO", "Maldonado": "UY-MA",
            "Montevideo": "UY-MO", "Paysandú": "UY-PA", "Rocha": "UY-RO", "Salto": "UY-SA",
            "Soriano": "UY-SO", "Tacuarembó": "UY-TA", "Treinta y Tres": "UY-TT",
        ],
        "Venezuela": [
            "Anzoátegui": "VE-B", "Aragua": "VE-D", "Barinas": "VE-E", "Bolívar": "VE-F",
            "Carabobo": "VE-G", "Distrito Capital": "VE-A", "Lara": "VE-K",
            "Miranda": "VE-M", "Mérida": "VE-L", "Nueva Esparta": "VE-O",
            "Portuguesa": "VE-P", "Táchira": "VE-S", "Vargas": "VE-X", "Yaracuy": "VE-U",
            "Zulia": "VE-V",
        ],
    ]
}
