import Foundation

/// Traduce la demarcación fina que ya guarda FontApp a su división administrativa
/// superior. Las claves son exactamente los valores medidos en producción.
///
/// En Latinoamérica Natural Earth ya da la primera división (estados, provincias,
/// departamentos), así que cada demarcación es su propio admin1 y no agrupa nada: se
/// apunta igual para que `backfill-admin1` no se niegue y para que `/zones` no las
/// meta en «otras regiones». Puerto Rico va como `US-PR`, que es su código ISO 3166-2.
///
/// Noruega: Natural Earth trae los 19 fylker de antes de 2020 y aquí se agrupan en los
/// condados actuales (ISO 3166-2 de 2024): Hedmark + Oppland → Innlandet, las dos Agder
/// → Agder, Hordaland + Sogn og Fjordane → Vestland y las dos Trøndelag → Trøndelag.
///
/// No se infiere por geometría: una provincia pertenece a una comunidad por definición.
/// Si entra un valor nuevo, queda sin clasificar hasta añadirlo explícitamente; inventar
/// aquí sería peor que devolver `nil`.
enum Admin1 {
    static func code(country: String?, region: String?) -> String? {
        guard let country, let region else { return nil }
        return byCountry[country]?[region]
    }

    static let byCountry: [String: [String: String]] = [
        "Andorra": [
            "Andorra la Vella": "AD-07", "Canillo": "AD-02", "Encamp": "AD-03",
            "Escaldes-Engordany": "AD-08", "La Massana": "AD-04", "Ordino": "AD-05",
            "Sant Julià de Lòria": "AD-06",
        ],
        "Argentina": [
            "Buenos Aires": "AR-B", "Catamarca": "AR-K", "Chaco": "AR-H", "Chubut": "AR-U",
            "Ciudad de Buenos Aires": "AR-C", "Corrientes": "AR-W", "Córdoba": "AR-X",
            "Entre Ríos": "AR-E", "Formosa": "AR-P", "Jujuy": "AR-Y", "La Pampa": "AR-L",
            "La Rioja": "AR-F", "Mendoza": "AR-M", "Misiones": "AR-N", "Neuquén": "AR-Q",
            "Río Negro": "AR-R", "Salta": "AR-A", "San Juan": "AR-J", "San Luis": "AR-D",
            "Santa Cruz": "AR-Z", "Santa Fe": "AR-S", "Santiago del Estero": "AR-G",
            "Tierra del Fuego": "AR-V", "Tucumán": "AR-T",
        ],
        "Bolivia": [
            "Chuquisaca": "BO-H", "Cochabamba": "BO-C", "El Beni": "BO-B", "La Paz": "BO-L",
            "Oruro": "BO-O", "Potosí": "BO-P", "Santa Cruz": "BO-S",
        ],
        "Brazil": [
            "Acre": "BR-AC", "Alagoas": "BR-AL", "Amazonas": "BR-AM", "Bahia": "BR-BA",
            "Ceará": "BR-CE", "Distrito Federal": "BR-DF", "Espírito Santo": "BR-ES",
            "Goiás": "BR-GO", "Maranhão": "BR-MA", "Mato Grosso": "BR-MT",
            "Mato Grosso do Sul": "BR-MS", "Minas Gerais": "BR-MG", "Paraná": "BR-PR",
            "Paraíba": "BR-PB", "Pará": "BR-PA", "Pernambuco": "BR-PE", "Piauí": "BR-PI",
            "Rio Grande do Norte": "BR-RN", "Rio Grande do Sul": "BR-RS",
            "Rio de Janeiro": "BR-RJ", "Rondônia": "BR-RO", "Roraima": "BR-RR",
            "Santa Catarina": "BR-SC", "Sergipe": "BR-SE", "São Paulo": "BR-SP",
            "Tocantins": "BR-TO",
        ],
        "Chile": [
            "Aisén del General Carlos Ibáñez del Campo": "CL-AI", "Antofagasta": "CL-AN",
            "Arica y Parinacota": "CL-AP", "Atacama": "CL-AT", "Bío-Bío": "CL-BI",
            "Coquimbo": "CL-CO", "La Araucanía": "CL-AR",
            "Libertador General Bernardo O'Higgins": "CL-LI", "Los Lagos": "CL-LL",
            "Los Ríos": "CL-LR", "Magallanes y Antártica Chilena": "CL-MA",
            "Maule": "CL-ML", "Región Metropolitana de Santiago": "CL-RM",
            "Valparaíso": "CL-VS", "Ñuble": "CL-NB",
        ],
        "Colombia": [
            "Amazonas": "CO-AMA", "Antioquia": "CO-ANT", "Arauca": "CO-ARA",
            "Atlántico": "CO-ATL", "Bogota": "CO-DC", "Bolívar": "CO-BOL",
            "Boyacá": "CO-BOY", "Caldas": "CO-CAL", "Caquetá": "CO-CAQ",
            "Casanare": "CO-CAS", "Cauca": "CO-CAU", "Cesar": "CO-CES", "Chocó": "CO-CHO",
            "Cundinamarca": "CO-CUN", "Córdoba": "CO-COR", "Huila": "CO-HUI",
            "La Guajira": "CO-LAG", "Magdalena": "CO-MAG", "Meta": "CO-MET",
            "Nariño": "CO-NAR", "Norte de Santander": "CO-NSA", "Putumayo": "CO-PUT",
            "Quindío": "CO-QUI", "Risaralda": "CO-RIS", "Santander": "CO-SAN",
            "Tolima": "CO-TOL", "Valle del Cauca": "CO-VAC", "Vichada": "CO-VID",
        ],
        "Costa Rica": [
            "Alajuela": "CR-A", "Cartago": "CR-C", "Guanacaste": "CR-G", "Heredia": "CR-H",
            "Limón": "CR-L", "Puntarenas": "CR-P", "San José": "CR-SJ",
        ],
        "Cuba": [
            "Artemisa": "CU-15", "Camagüey": "CU-09", "Ciego de Ávila": "CU-08",
            "Cienfuegos": "CU-06", "Ciudad de la Habana": "CU-03", "Granma": "CU-12",
            "Holguín": "CU-11", "Isla de la Juventud": "CU-99", "Las Tunas": "CU-10",
            "Matanzas": "CU-04", "Mayabeque": "CU-16", "Pinar del Río": "CU-01",
            "Sancti Spíritus": "CU-07", "Santiago de Cuba": "CU-13", "Villa Clara": "CU-05",
        ],
        "Dominican Republic": [
            "Azua": "DO-02", "Distrito Nacional": "DO-01", "Duarte": "DO-06",
            "Independencia": "DO-10", "La Altagracia": "DO-11", "La Vega": "DO-13",
            "María Trinidad Sánchez": "DO-14", "Monte Cristi": "DO-15",
            "Puerto Plata": "DO-18", "San Cristóbal": "DO-21", "San José de Ocoa": "DO-31",
            "San Juan": "DO-22", "Santiago": "DO-25", "Santo Domingo": "DO-32",
        ],
        "Ecuador": [
            "Azuay": "EC-A", "Bolivar": "EC-B", "Carchi": "EC-C", "Cañar": "EC-F",
            "Chimborazo": "EC-H", "Cotopaxi": "EC-X", "El Oro": "EC-O",
            "Esmeraldas": "EC-E", "Galápagos": "EC-W", "Guayas": "EC-G", "Imbabura": "EC-I",
            "Loja": "EC-L", "Los Rios": "EC-R", "Manabi": "EC-M", "Morona Santiago": "EC-S",
            "Napo": "EC-N", "Pastaza": "EC-Y", "Pichincha": "EC-P", "Santa Elena": "EC-SE",
            "Santo Domingo de los Tsáchilas": "EC-SD", "Sucumbios": "EC-U",
            "Tungurahua": "EC-T", "Zamora Chinchipe": "EC-Z",
        ],
        "El Salvador": [
            "La Unión": "SV-UN", "San Salvador": "SV-SS", "Santa Ana": "SV-SA",
            "Sonsonate": "SV-SO", "Usulután": "SV-US",
        ],
        "Finland": [
            "Central Finland": "FI-08", "Central Ostrobothnia": "FI-07",
            "Finland Proper": "FI-19", "Kainuu": "FI-05", "Kymenlaakso": "FI-09",
            "Lapland": "FI-10", "North Karelia": "FI-13", "Northern Ostrobothnia": "FI-14",
            "Northern Savonia": "FI-15", "Ostrobothnia": "FI-12", "Pirkanmaa": "FI-11",
            "Päijät-Häme": "FI-16", "Satakunta": "FI-17", "South Karelia": "FI-02",
            "Southern Ostrobothnia": "FI-03", "Southern Savonia": "FI-04",
            "Tavastia Proper": "FI-06", "Uusimaa": "FI-18", "Åland": "FI-01",
        ],
        "France": [
            "Ardèche": "FR-ARA", "Ariège": "FR-OCC", "Aude": "FR-OCC",
            "Aveyron": "FR-OCC", "Bouches-du-Rhône": "FR-PAC", "Cantal": "FR-ARA",
            "Corrèze": "FR-NAQ", "Dordogne": "FR-NAQ", "Drôme": "FR-ARA",
            "Gard": "FR-OCC", "Gers": "FR-OCC", "Gironde": "FR-NAQ",
            "Haute-Garonne": "FR-OCC", "Haute-Loire": "FR-ARA",
            "Hautes-Pyrénées": "FR-OCC", "Hérault": "FR-OCC", "Landes": "FR-NAQ",
            "Lot": "FR-OCC", "Lot-et-Garonne": "FR-NAQ", "Lozère": "FR-OCC",
            "Pyrénées-Atlantiques": "FR-NAQ", "Pyrénées-Orientales": "FR-OCC",
            "Tarn": "FR-OCC", "Tarn-et-Garonne": "FR-OCC", "Vaucluse": "FR-PAC",
        ],
        "Guatemala": [
            "Baja Verapaz": "GT-15", "Chimaltenango": "GT-04", "Guatemala": "GT-01",
            "Izabal": "GT-18", "Petén": "GT-17", "Sacatepéquez": "GT-03",
            "San Marcos": "GT-12", "Sololá": "GT-07", "Suchitepéquez": "GT-10",
            "Totonicapán": "GT-08",
        ],
        "Honduras": [
            "Atlántida": "HN-AT", "Cortés": "HN-CR", "Francisco Morazán": "HN-FM",
            "Gracias a Dios": "HN-GD", "Islas de la Bahía": "HN-IB", "La Paz": "HN-LP",
            "Lempira": "HN-LE", "Olancho": "HN-OL", "Yoro": "HN-YO",
        ],
        "Italy": [
            "Agrigento": "IT-82", "Alessandria": "IT-21", "Ancona": "IT-57",
            "Aoste": "IT-23", "Arezzo": "IT-52", "Ascoli Piceno": "IT-57", "Asti": "IT-21",
            "Avellino": "IT-72", "Bari": "IT-75", "Barletta-Andria Trani": "IT-75",
            "Belluno": "IT-34", "Benevento": "IT-72", "Bergamo": "IT-25", "Biella": "IT-21",
            "Bologna": "IT-45", "Bozen": "IT-32", "Brescia": "IT-25", "Brindisi": "IT-75",
            "Cagliari": "IT-88", "Caltanissetta": "IT-82", "Campobasso": "IT-67",
            "Carbonia-Iglesias": "IT-88", "Caserta": "IT-72", "Catania": "IT-82",
            "Catanzaro": "IT-78", "Chieti": "IT-65", "Como": "IT-25", "Cosenza": "IT-78",
            "Cremona": "IT-25", "Crotene": "IT-78", "Cuneo": "IT-21", "Enna": "IT-82",
            "Fermo": "IT-57", "Ferrara": "IT-45", "Firenze": "IT-52", "Foggia": "IT-75",
            "Forlì-Cesena": "IT-45", "Frosinone": "IT-62", "Genova": "IT-42",
            "Gorizia": "IT-36", "Grosseto": "IT-52", "Imperia": "IT-42", "Isernia": "IT-67",
            "L'Aquila": "IT-65", "La Spezia": "IT-42", "Latina": "IT-62", "Lecce": "IT-75",
            "Lecco": "IT-25", "Livorno": "IT-52", "Lodi": "IT-25", "Lucca": "IT-52",
            "Macerata": "IT-57", "Mantova": "IT-25", "Massa-Carrara": "IT-52",
            "Matera": "IT-77", "Medio Campidano": "IT-88", "Messina": "IT-82",
            "Milano": "IT-25", "Modena": "IT-45", "Monza e Brianza": "IT-25",
            "Napoli": "IT-72", "Novara": "IT-21", "Nuoro": "IT-88", "Ogliastra": "IT-88",
            "Olbia-Tempio": "IT-88", "Oristrano": "IT-88", "Padova": "IT-34",
            "Palermo": "IT-82", "Parma": "IT-45", "Pavia": "IT-25", "Perugia": "IT-55",
            "Pesaro e Urbino": "IT-57", "Pescara": "IT-65", "Piacenza": "IT-45",
            "Pisa": "IT-52", "Pistoia": "IT-52", "Pordenone": "IT-36", "Potenza": "IT-77",
            "Prato": "IT-52", "Ragusa": "IT-82", "Ravenna": "IT-45",
            "Reggio Calabria": "IT-78", "Reggio Emilia": "IT-45", "Rieti": "IT-62",
            "Rimini": "IT-45", "Roma": "IT-62", "Rovigo": "IT-34", "Salerno": "IT-72",
            "Sassari": "IT-88", "Savona": "IT-42", "Siena": "IT-52", "Siracusa": "IT-82",
            "Sondrio": "IT-25", "Taranto": "IT-75", "Teramo": "IT-65", "Terni": "IT-55",
            "Trapani": "IT-82", "Trento": "IT-32", "Treviso": "IT-34", "Trieste": "IT-36",
            "Turin": "IT-21", "Udine": "IT-36", "Varese": "IT-25", "Venezia": "IT-34",
            "Verbano-Cusio-Ossola": "IT-21", "Vercelli": "IT-21", "Verona": "IT-34",
            "Vibo Valentia": "IT-78", "Vicenza": "IT-34", "Viterbo": "IT-62",
        ],
        "Mexico": [
            "Aguascalientes": "MX-AGU", "Baja California": "MX-BCN",
            "Baja California Sur": "MX-BCS", "Campeche": "MX-CAM", "Chiapas": "MX-CHP",
            "Chihuahua": "MX-CHH", "Coahuila": "MX-COA", "Colima": "MX-COL",
            "Distrito Federal": "MX-CMX", "Durango": "MX-DUR", "Guanajuato": "MX-GUA",
            "Guerrero": "MX-GRO", "Hidalgo": "MX-HID", "Jalisco": "MX-JAL",
            "Michoacán": "MX-MIC", "Morelos": "MX-MOR", "México": "MX-MEX",
            "Nayarit": "MX-NAY", "Nuevo León": "MX-NLE", "Oaxaca": "MX-OAX",
            "Puebla": "MX-PUE", "Querétaro": "MX-QUE", "Quintana Roo": "MX-ROO",
            "San Luis Potosí": "MX-SLP", "Sinaloa": "MX-SIN", "Sonora": "MX-SON",
            "Tabasco": "MX-TAB", "Tamaulipas": "MX-TAM", "Tlaxcala": "MX-TLA",
            "Veracruz": "MX-VER", "Yucatán": "MX-YUC", "Zacatecas": "MX-ZAC",
        ],
        "Nicaragua": [
            "Atlántico Norte": "NI-AN", "Atlántico Sur": "NI-AS", "Boaco": "NI-BO",
            "Carazo": "NI-CA", "Chinandega": "NI-CI", "León": "NI-LE", "Madriz": "NI-MD",
            "Managua": "NI-MN", "Rivas": "NI-RI",
        ],
        "Norway": [
            "Akershus": "NO-32", "Aust-Agder": "NO-42", "Buskerud": "NO-33",
            "Finnmark": "NO-56", "Hedmark": "NO-34", "Hordaland": "NO-46",
            "Møre og Romsdal": "NO-15", "Nord-Trøndelag": "NO-50", "Nordland": "NO-18",
            "Oppland": "NO-34", "Oslo": "NO-03", "Rogaland": "NO-11",
            "Sogn og Fjordane": "NO-46", "Svalbard": "NO-21", "Sør-Trøndelag": "NO-50",
            "Telemark": "NO-40", "Troms": "NO-55", "Vest-Agder": "NO-42",
            "Vestfold": "NO-39", "Østfold": "NO-31",
        ],
        "Panama": [
            "Bocas del Toro": "PA-1", "Chiriquí": "PA-4", "Coclé": "PA-2", "Colón": "PA-3",
            "Panama": "PA-8", "Veraguas": "PA-9",
        ],
        "Paraguay": [
            "Alto Paraná": "PY-10", "Amambay": "PY-13", "Asunción": "PY-ASU",
            "Boquerón": "PY-19", "Canindeyú": "PY-14", "Central": "PY-11",
            "Cordillera": "PY-3", "Guairá": "PY-4", "Itapúa": "PY-7", "Misiones": "PY-8",
            "Paraguarí": "PY-9",
        ],
        "Peru": [
            "Amazonas": "PE-AMA", "Ancash": "PE-ANC", "Apurímac": "PE-APU",
            "Arequipa": "PE-ARE", "Ayacucho": "PE-AYA", "Cajamarca": "PE-CAJ",
            "Callao": "PE-CAL", "Cusco": "PE-CUS", "Huancavelica": "PE-HUV",
            "Huánuco": "PE-HUC", "Ica": "PE-ICA", "Junín": "PE-JUN",
            "La Libertad": "PE-LAL", "Lambayeque": "PE-LAM", "Lima": "PE-LIM",
            "Lima Province": "PE-LMA", "Loreto": "PE-LOR", "Madre de Dios": "PE-MDD",
            "Puno": "PE-PUN", "San Martín": "PE-SAM", "Tacna": "PE-TAC",
        ],
        "Portugal": [
            "Aveiro": "PT-01", "Azores": "PT-20", "Beja": "PT-02", "Braga": "PT-03",
            "Bragança": "PT-04", "Castelo Branco": "PT-05", "Coimbra": "PT-06",
            "Faro": "PT-08", "Guarda": "PT-09", "Leiria": "PT-10", "Lisboa": "PT-11",
            "Madeira": "PT-30", "Portalegre": "PT-12", "Porto": "PT-13",
            "Santarém": "PT-14", "Setúbal": "PT-15", "Viana do Castelo": "PT-16",
            "Vila Real": "PT-17", "Viseu": "PT-18", "Évora": "PT-07",
        ],
        "Puerto Rico": [
            "Puerto Rico": "US-PR",
        ],
        "Spain": [
            "Albacete": "ES-CM", "Alicante": "ES-VC", "Almería": "ES-AN",
            "Asturias": "ES-AS", "Badajoz": "ES-EX", "Baleares": "ES-IB",
            "Barcelona": "ES-CT", "Bizkaia": "ES-PV", "Burgos": "ES-CL",
            "Cantabria": "ES-CB", "Castellón": "ES-VC", "Ceuta": "ES-CE",
            "Ciudad Real": "ES-CM", "Cuenca": "ES-CM", "Cáceres": "ES-EX",
            "Cádiz": "ES-AN", "Córdoba": "ES-AN", "Gipuzkoa": "ES-PV",
            "Gerona": "ES-CT", "Girona": "ES-CT", "Granada": "ES-AN", "Guadalajara": "ES-CM",
            "Huelva": "ES-AN", "Huesca": "ES-AR", "Jaén": "ES-AN",
            "La Coruña": "ES-GA", "La Rioja": "ES-RI", "Las Palmas": "ES-CN",
            "León": "ES-CL", "Lérida": "ES-CT", "Lleida": "ES-CT", "Lugo": "ES-GA",
            "Madrid": "ES-MD",
            "Melilla": "ES-ML", "Murcia": "ES-MC", "Málaga": "ES-AN",
            "Navarra": "ES-NC", "Orense": "ES-GA", "Palencia": "ES-CL",
            "Pontevedra": "ES-GA", "Salamanca": "ES-CL", "Santa Cruz de Tenerife": "ES-CN",
            "Segovia": "ES-CL", "Sevilla": "ES-AN", "Soria": "ES-CL",
            "Tarragona": "ES-CT", "Teruel": "ES-AR", "Toledo": "ES-CM",
            "Valencia": "ES-VC", "Valladolid": "ES-CL", "Zamora": "ES-CL",
            "Zaragoza": "ES-AR", "Álava": "ES-PV", "Ávila": "ES-CL",
        ],
        "Sweden": [
            "Blekinge": "SE-K", "Dalarna": "SE-W", "Gotland": "SE-I",
            "Gävleborg": "SE-X", "Halland": "SE-N", "Jämtland": "SE-Z",
            "Jönköping": "SE-F", "Kalmar": "SE-H", "Kronoberg": "SE-G",
            "Norrbotten": "SE-BD", "Orebro": "SE-T", "Skåne": "SE-M",
            "Stockholm": "SE-AB", "Södermanland": "SE-D", "Uppsala": "SE-C",
            "Värmland": "SE-S", "Västerbotten": "SE-AC", "Västernorrland": "SE-Y",
            "Västmanland": "SE-U", "Västra Götaland": "SE-O", "Östergötland": "SE-E",
        ],
        "Switzerland": [
            "Aargau": "CH-AG", "Appenzell Ausserrhoden": "CH-AR",
            "Appenzell Innerrhoden": "CH-AI", "Basel-Landschaft": "CH-BL",
            "Basel-Stadt": "CH-BS", "Bern": "CH-BE", "Fribourg": "CH-FR",
            "Genève": "CH-GE", "Glarus": "CH-GL", "Graubünden": "CH-GR",
            "Jura": "CH-JU", "Lucerne": "CH-LU", "Neuchâtel": "CH-NE",
            "Nidwalden": "CH-NW", "Obwalden": "CH-OW", "Sankt Gallen": "CH-SG",
            "Schaffhausen": "CH-SH", "Schwyz": "CH-SZ", "Solothurn": "CH-SO",
            "Thurgau": "CH-TG", "Ticino": "CH-TI", "Uri": "CH-UR",
            "Valais": "CH-VS", "Vaud": "CH-VD", "Zug": "CH-ZG", "Zürich": "CH-ZH",
        ],
        "Uruguay": [
            "Canelones": "UY-CA", "Colonia": "UY-CO", "Maldonado": "UY-MA",
            "Montevideo": "UY-MO", "Paysandú": "UY-PA", "Rocha": "UY-RO", "Salto": "UY-SA",
            "Soriano": "UY-SO", "Tacuarembó": "UY-TA", "Treinta y Tres": "UY-TT",
        ],
        "Venezuela": [
            "Anzoátegui": "VE-B", "Aragua": "VE-D", "Barinas": "VE-E", "Bolívar": "VE-F",
            "Carabobo": "VE-G", "Distrito Capital": "VE-A", "Lara": "VE-K",
            "Miranda": "VE-M", "Mérida": "VE-L", "Nueva Esparta": "VE-O",
            "Portuguesa": "VE-P", "Táchira": "VE-S", "Vargas": "VE-X", "Yaracuy": "VE-U",
            "Zulia": "VE-V",
        ],
    ]
}
